### ISSUE TITLE
The replay bot is running into a wall on its map record run

### ISSUE THREAD

**Issue by Disillusioned1** [MestroGroup/mgTimer-Public#34] opened 2020-07-19 13:06 UTC
The replay bot when selected to display its run, proceeded to begin by running into a wall for the full 4 minute duration of the 'replay'. This was on Surf_Rookie replaying a run set by Qrvy. 

The mouse movements of the bot still seem to be mimicking ramp movement, but it is all done while staring at a wall.

Edit: After the record was beat the replay bot proceeded to show the first part of the run correctly and then after 20 seconds the same issue arose.

**Comment by qrvyboi** [comment] 2020-07-19 23:07
Issue with running into the wall seems to be non-recurrent or difficult to replicate.

However, the bot is now lagging mid-run and causing it to be thrown off somehow, displaying again the map record, just not on the actual ramps, but rather flying through the air randomly around the map.

**Comment by MestroGroup** [comment] 2020-07-19 23:09
This could be related to records made before I tweaked physics. Confirm new
replays are still buggy or OK?

**Comment by qrvyboi** [comment] 2020-07-19 23:12
New records are still buggy. Seems to be reoccurring at the same spot on each map, e.g: Stage 9/10 transition on surf_Rookie.

Could possibly be an issue with stage transitions and the physics surrounding them?

**Comment by MestroGroup** [comment] 2020-07-25 16:24
Database reset for hotfix on 26/07 - Reproduction steps required.

**Comment by MestroGroup** [comment] 2020-07-27 14:44
Testing produced no further issues - Closing unless further issues detected.

**Closed as completed by MestroGroup** 2020-07-27 14:44 UTC
Labels: reproduction-required
