### ISSUE TITLE
Speedometer issues with tracking speed correctly

### ISSUE THREAD

**Issue by Disillusioned1** [MestroGroup/mgTimer-Public#35] opened 2020-07-19 13:13 UTC
The speedometer seems to successfully follow my speed, however on certain occasions (unsure exactly what occurs for it to break), but the speedometer will read 300 u/s when actually I am travelling at 3,000+. This has also occurred with it reporting 100 u/s when actually travelling at 1,000+

**Comment by qrvyboi** [comment] 2020-07-19 23:09
Seems to be that the speedometer is displaying 1/10th of the current speed.

Was easy to reproduce, however still unsure as to how it's occurring. Only inference I can make so far is that it occurs more regularly when strafing mid jump than when on a ramp.

**Comment by MestroGroup** [comment] 2020-07-25 16:22
This is due to HUD cutoff, will monitor this.

**Comment by MestroGroup** [comment] 2020-07-27 14:44
Testing produced no further issues - Closing unless further issues detected.

**Closed as completed by MestroGroup** 2020-07-27 14:44 UTC
Labels: bug
