### ISSUE TITLE
replay bot buggy

### ISSUE THREAD

**Issue by cynlik** [MestroGroup/mgTimer-Public#39] opened 2020-07-19 23:12 UTC
expected to replay stage 3 times and then stop

instead repeats stage seemingly random amount of times 
also found that sometimes bot will stop replaying stage 2+ and go back to stage 1 repeating it seemingly random amount of times

**Comment by cynlik** [comment] 2020-07-19 23:13
overall, bots still seem a bit bugged and their behaviour is somewhat erratical, can't be predicted always

**Comment by cynlik** [comment] 2020-07-19 23:14
furthermore, can not always force bot to replay another stage. says: bot already in use in red colour

**Comment by MestroGroup** [comment] 2020-07-19 23:15
I updated stage bots to repeat the selected stage.

**Comment by qrvyboi** [comment] 2020-07-19 23:17
-> First stage is looping constantly rather than the bot resetting and being static.

-> Bot is not being named correctly with the corresponding replay being shown.

-> Bot instantly resets to looping the first stage once the selected record that is playing is over.

**Comment by cynlik** [comment] 2020-07-19 23:18
replay bot for whole map also seems to give up on run and rather run into walls or fly or stay stuck and the run won't end at the right time

**Comment by qrvyboi** [comment] 2020-07-19 23:19
Map replay issue has been reported elsewhere and elaborated upon with the exact bugs and how they are reproduced/where they reproduce.

**Comment by qrvyboi** [comment] 2020-07-19 23:21
Stage record replay bot is now looping the correct stage and seems to be functional. However, it is resetting still to looping the first stage a few times, then fully resetting to being static.

edit: bot is renaming correctly.

**Comment by ItsNotSpaghetti** [comment] 2020-07-19 23:23
bot glitch after stage 8. flying https://drive.google.com/file/d/1OIWY-QLe1mjm3R4gwnbXicX5ULeFjtvA/view?usp=sharing

**Comment by MestroGroup** [comment] 2020-07-27 14:44
Testing produced no further issues - Closing unless further issues detected.

**Closed as completed by MestroGroup** 2020-07-27 14:44 UTC
